jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | as_text }}"
      database: DEV
      warehouse: INTEGRATION
      schema: ELLIOT
      threads: 24

cicd_test:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'cicd_test.duckdb'
      extensions:
        - httpfs
        - parquet
      # settings:
      #   s3_region: my-aws-region
      #   s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
      #   s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"